services:
  - type: web
    name: food-dongxgll
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DB_PATH
        value: /opt/render/project/src/data/food-waste.db
